namespace: kolter
name: callback
version: 1.0
readme: README.md
authors:
  - Emmanuel Bouthenot <kolter@openics.org>
description: Provides alternative stdout callback plugins
license_file: LICENSE
tags: [callback, stdout, print]
repository: https://github.com/k0lter/ansible-callback.git
documentation: null
homepage: https://github.com/k0lter/ansible-callback
issues: https://github.com/k0lter/ansible-callback/issues
